import Head from "next/head";

interface HeadComponentInteface {
  title: string;
}

const HeadComponent = ({ title }: HeadComponentInteface) => (
  <Head>
    <title>{title}</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
  </Head>
);

export default HeadComponent;
