version: "3.7"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: tweet
    volumes:
      - tweet-db:/var/lib/mysql
    ports:
      - 3306:3306
  nestjs:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    depends_on:
      - mysql
    command: yarn start
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root123456
      MYSQL_DATABASE: tweet
      MYSQL_PORT: 3306
      JWT_SECRET: secret
volumes:
  tweet-db:
